language: python
python: 2.7

before_install:
  - sudo add-apt-repository -y ppa:webupd8team/java
  - sudo apt-get update -qq
  - sudo apt-get install -y curl

install:
  # Install Transcrypt
  - git clone https://github.com/elasticdog/transcrypt.git
  - sudo ln -s ${PWD}/transcrypt/transcrypt /usr/local/bin/transcrypt
  - transcrypt -y -c aes-256-cbc -p $TRANSCRYPT_KEY

  # Install Ansible
  - pip install ansible==2.1

  # Install Java 8
  - sudo apt-get install oracle-java8-set-default

script:
  - transcrypt --display
  - java -version
  - javac -version
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
  - ./gradlew build -PappVersion=$TRAVIS_BUILD_NUMBER
  - cd provision
  - export ANSIBLE_ROLES_PATH=$PWD/ansible_roles/
  - export ANSIBLE_HOST_KEY_CHECKING=False
  - eval `ssh-agent -s`
  - ssh-add protected/digitalocean.pem
  - ansible-galaxy install -r requirements.yml -p $ANSIBLE_ROLES_PATH
  - ansible-playbook -i production.hosts deploy-playbook.yml --extra-vars "appVersion=$TRAVIS_BUILD_NUMBER"

env:
  global:
    secure: "L+Yqcx3Z4DY+LQKtenrAS/Yc049GlKLas4pAtiHwUevEQx2HdhTbe1i3ZRtIhfmIFLOC3GwETQmum6JmblqgfJLP5bo2EJskE8PGF6O53hnspUlqXUAlzMyFDqs1pxrnOn9aMSViqKgaMtwFgVTFRE+4SXMb9pEyhIRf6TsnEDLMkC3Wo4z4um24+OTxkT3g90vHGfsE5oS8Gug2MZloA9c0KQCJkkE5Ja4tm+Uv0+jJocjtLy5NPUi/GgcjtJZdA9t1Xa4ddWX0zvpg29Dm535HtE4SNcXGXS+Iy+eY2T6QBQN0/7+Gd+wK5GoYkpta5maTOq+CKhe2q5IEaOkGKCdPNV7npQcbmT1MwB9K/W4PjytYlLwuFpNfJkxmsOyesWwt/qntjmb/53Bm3B/Q/v470liORWkD9SelszoNmkFRW8MsN+VSuQAJJglv8FnEwWsJ1VHKmEx26zqZXNrn21X9M3OHqCu6WsrctkmPY/mp0nOJjchckTxBe2VEHG1FDzgTzEjxUYtts7tyTbZ/2jU4w0YtHS4mhJ8GCiDQ/wy8MYgqMuc1JhBNy25IXKtd25NdwQozqtOfQwzHhBmToJK8fUkfP+106F7SQrSUfMDSQFfPEY8K/Yxe9WEGHceitA+Um+avJhz23d9t1woNsy88KjpIphEHJ9CzTc0tnko="