language: python
python: 2.7

before_install:
  - sudo add-apt-repository ppa:webupd8team/java
  - sudo apt-get update -qq
  - sudo apt-get install -y curl

install:
  # Install Transcrypt
  - git clone https://github.com/elasticdog/transcrypt.git
  - sudo ln -s ${PWD}/transcrypt/transcrypt /usr/local/bin/transcrypt

  # Install Ansible
  - pip install ansible==2.1

  # Install Java 8
  - sudo apt-get install oracle-java8-installer

script:
  - ./gradlew build -PappVersion=$TRAVIS_BUILD_NUMBER
  - ansible-playbook -i /provision/production.hosts /provision/deploy-playbook.yml --extra-vars "appVersion=$TRAVIS_BUILD_NUMBER"

env:
  global:
    secure:

    # $ sudo apt-get install oracle-java8-set-default